export const LOAD_NEWS_START = "LOAD_NEWS_START";
export const LOAD_NEWS_SUCCESS = "LOAD_NEWS_SUCCESS";
export const LOAD_NEWS_ERROR = "LOAD_NEWS_ERROR";

export const SET_IS_ALL_MARKETNEWS = "SET_IS_ALL_MARKETNEWS";
export const SET_IS_ALL_PROJECTNEWS = "SET_IS_ALL_PROJECTNEWS";

